### test_api
GET http://localhost:3003/ping

### all_users
GET http://localhost:3003/users

### all_products
GET http://localhost:3003/products

### product_by_name
GET http://localhost:3003/product?name=ga